// Generated by gencpp from file av_messages/destination.msg
// DO NOT EDIT!


#ifndef AV_MESSAGES_MESSAGE_DESTINATION_H
#define AV_MESSAGES_MESSAGE_DESTINATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace av_messages
{
template <class ContainerAllocator>
struct destination_
{
  typedef destination_<ContainerAllocator> Type;

  destination_()
    : header()
    , latitude(0.0)
    , longitude(0.0)  {
    }
  destination_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude(0.0)
    , longitude(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _latitude_type;
  _latitude_type latitude;

   typedef float _longitude_type;
  _longitude_type longitude;





  typedef boost::shared_ptr< ::av_messages::destination_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::av_messages::destination_<ContainerAllocator> const> ConstPtr;

}; // struct destination_

typedef ::av_messages::destination_<std::allocator<void> > destination;

typedef boost::shared_ptr< ::av_messages::destination > destinationPtr;
typedef boost::shared_ptr< ::av_messages::destination const> destinationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::av_messages::destination_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::av_messages::destination_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::av_messages::destination_<ContainerAllocator1> & lhs, const ::av_messages::destination_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::av_messages::destination_<ContainerAllocator1> & lhs, const ::av_messages::destination_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace av_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::av_messages::destination_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::av_messages::destination_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::av_messages::destination_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::av_messages::destination_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::av_messages::destination_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::av_messages::destination_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::av_messages::destination_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79197bb5a58d33017c590e24adb874d5";
  }

  static const char* value(const ::av_messages::destination_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79197bb5a58d3301ULL;
  static const uint64_t static_value2 = 0x7c590e24adb874d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::av_messages::destination_<ContainerAllocator> >
{
  static const char* value()
  {
    return "av_messages/destination";
  }

  static const char* value(const ::av_messages::destination_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::av_messages::destination_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A standard message for the global target coordinates\n"
"std_msgs/Header header \n"
"\n"
"float32 latitude\n"
"float32 longitude\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::av_messages::destination_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::av_messages::destination_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude);
      stream.next(m.longitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct destination_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::av_messages::destination_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::av_messages::destination_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AV_MESSAGES_MESSAGE_DESTINATION_H
