// Generated by gencpp from file av_messages/objects.msg
// DO NOT EDIT!


#ifndef AV_MESSAGES_MESSAGE_OBJECTS_H
#define AV_MESSAGES_MESSAGE_OBJECTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <av_messages/object.h>

namespace av_messages
{
template <class ContainerAllocator>
struct objects_
{
  typedef objects_<ContainerAllocator> Type;

  objects_()
    : header()
    , object_detections()  {
    }
  objects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , object_detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::av_messages::object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::av_messages::object_<ContainerAllocator> >::other >  _object_detections_type;
  _object_detections_type object_detections;





  typedef boost::shared_ptr< ::av_messages::objects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::av_messages::objects_<ContainerAllocator> const> ConstPtr;

}; // struct objects_

typedef ::av_messages::objects_<std::allocator<void> > objects;

typedef boost::shared_ptr< ::av_messages::objects > objectsPtr;
typedef boost::shared_ptr< ::av_messages::objects const> objectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::av_messages::objects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::av_messages::objects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::av_messages::objects_<ContainerAllocator1> & lhs, const ::av_messages::objects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.object_detections == rhs.object_detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::av_messages::objects_<ContainerAllocator1> & lhs, const ::av_messages::objects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace av_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::av_messages::objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::av_messages::objects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::av_messages::objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::av_messages::objects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::av_messages::objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::av_messages::objects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::av_messages::objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29c2393b11acc79632a74bbd645a8019";
  }

  static const char* value(const ::av_messages::objects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29c2393b11acc796ULL;
  static const uint64_t static_value2 = 0x32a74bbd645a8019ULL;
};

template<class ContainerAllocator>
struct DataType< ::av_messages::objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "av_messages/objects";
  }

  static const char* value(const ::av_messages::objects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::av_messages::objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"av_messages/object[] object_detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: av_messages/object\n"
"# A standard object message for perception\n"
"\n"
"geometry_msgs/Point position # position in x, y ,z in meters\n"
"std_msgs/String class # string for the actual object class, i.e. tree, pedestrian, car, truck, etc.\n"
"\n"
"std_msgs/String status # wether the object is static/dynamic in nature etc.\n"
"geometry_msgs/Pose2D object_state_dt # Velocity in x, y, theta of a dynamic object\n"
"\n"
"std_msgs/Int16 id # unique object id for every object\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int16\n"
"int16 data\n"
;
  }

  static const char* value(const ::av_messages::objects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::av_messages::objects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.object_detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct objects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::av_messages::objects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::av_messages::objects_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "object_detections[]" << std::endl;
    for (size_t i = 0; i < v.object_detections.size(); ++i)
    {
      s << indent << "  object_detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::av_messages::object_<ContainerAllocator> >::stream(s, indent + "    ", v.object_detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AV_MESSAGES_MESSAGE_OBJECTS_H
