// Generated by gencpp from file av_messages/trafficLights.msg
// DO NOT EDIT!


#ifndef AV_MESSAGES_MESSAGE_TRAFFICLIGHTS_H
#define AV_MESSAGES_MESSAGE_TRAFFICLIGHTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <std_msgs/String.h>
#include <std_msgs/Int16.h>

namespace av_messages
{
template <class ContainerAllocator>
struct trafficLights_
{
  typedef trafficLights_<ContainerAllocator> Type;

  trafficLights_()
    : position()
    , class()
    , id()  {
    }
  trafficLights_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , class(_alloc)
    , id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::std_msgs::String_<ContainerAllocator>  _class_type;
  _class_type class;

   typedef  ::std_msgs::Int16_<ContainerAllocator>  _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::av_messages::trafficLights_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::av_messages::trafficLights_<ContainerAllocator> const> ConstPtr;

}; // struct trafficLights_

typedef ::av_messages::trafficLights_<std::allocator<void> > trafficLights;

typedef boost::shared_ptr< ::av_messages::trafficLights > trafficLightsPtr;
typedef boost::shared_ptr< ::av_messages::trafficLights const> trafficLightsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::av_messages::trafficLights_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::av_messages::trafficLights_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::av_messages::trafficLights_<ContainerAllocator1> & lhs, const ::av_messages::trafficLights_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.class == rhs.class &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::av_messages::trafficLights_<ContainerAllocator1> & lhs, const ::av_messages::trafficLights_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace av_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::av_messages::trafficLights_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::av_messages::trafficLights_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::av_messages::trafficLights_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::av_messages::trafficLights_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::av_messages::trafficLights_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::av_messages::trafficLights_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::av_messages::trafficLights_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ca47be3250ec12d6b540eb18eb643e2";
  }

  static const char* value(const ::av_messages::trafficLights_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ca47be3250ec12dULL;
  static const uint64_t static_value2 = 0x6b540eb18eb643e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::av_messages::trafficLights_<ContainerAllocator> >
{
  static const char* value()
  {
    return "av_messages/trafficLights";
  }

  static const char* value(const ::av_messages::trafficLights_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::av_messages::trafficLights_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position # position in x, y ,z in meters\n"
"\n"
"std_msgs/String class # string for the light mode\n"
"\n"
"std_msgs/Int16 id # unique object id for every traffic light\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int16\n"
"int16 data\n"
;
  }

  static const char* value(const ::av_messages::trafficLights_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::av_messages::trafficLights_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.class);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct trafficLights_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::av_messages::trafficLights_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::av_messages::trafficLights_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "class: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.class);
    s << indent << "id: ";
    s << std::endl;
    Printer< ::std_msgs::Int16_<ContainerAllocator> >::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AV_MESSAGES_MESSAGE_TRAFFICLIGHTS_H
