# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from av_messages/object.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class object(genpy.Message):
  _md5sum = "3d13e84609bddf054577bea1e144b7e8"
  _type = "av_messages/object"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# A standard object message for perception

geometry_msgs/Point position # position in x, y ,z in meters
std_msgs/String class # string for the actual object class, i.e. tree, pedestrian, car, truck, etc.

std_msgs/String status # wether the object is static/dynamic in nature etc.
geometry_msgs/Pose2D object_state_dt # Velocity in x, y, theta of a dynamic object

std_msgs/Int16 id # unique object id for every object
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: geometry_msgs/Pose2D
# Deprecated
# Please use the full 3D pose.

# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.

# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.


# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta

================================================================================
MSG: std_msgs/Int16
int16 data
"""
  __slots__ = ['position','class_','status','object_state_dt','id']
  _slot_types = ['geometry_msgs/Point','std_msgs/String','std_msgs/String','geometry_msgs/Pose2D','std_msgs/Int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,class_,status,object_state_dt,id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(object, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.class_ is None:
        self.class_ = std_msgs.msg.String()
      if self.status is None:
        self.status = std_msgs.msg.String()
      if self.object_state_dt is None:
        self.object_state_dt = geometry_msgs.msg.Pose2D()
      if self.id is None:
        self.id = std_msgs.msg.Int16()
    else:
      self.position = geometry_msgs.msg.Point()
      self.class_ = std_msgs.msg.String()
      self.status = std_msgs.msg.String()
      self.object_state_dt = geometry_msgs.msg.Pose2D()
      self.id = std_msgs.msg.Int16()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d().pack(_x.position.x, _x.position.y, _x.position.z))
      _x = self.class_.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.status.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3dh().pack(_x.object_state_dt.x, _x.object_state_dt.y, _x.object_state_dt.theta, _x.id.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.class_ is None:
        self.class_ = std_msgs.msg.String()
      if self.status is None:
        self.status = std_msgs.msg.String()
      if self.object_state_dt is None:
        self.object_state_dt = geometry_msgs.msg.Pose2D()
      if self.id is None:
        self.id = std_msgs.msg.Int16()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.position.x, _x.position.y, _x.position.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status.data = str[start:end]
      _x = self
      start = end
      end += 26
      (_x.object_state_dt.x, _x.object_state_dt.y, _x.object_state_dt.theta, _x.id.data,) = _get_struct_3dh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d().pack(_x.position.x, _x.position.y, _x.position.z))
      _x = self.class_.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.status.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3dh().pack(_x.object_state_dt.x, _x.object_state_dt.y, _x.object_state_dt.theta, _x.id.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.class_ is None:
        self.class_ = std_msgs.msg.String()
      if self.status is None:
        self.status = std_msgs.msg.String()
      if self.object_state_dt is None:
        self.object_state_dt = geometry_msgs.msg.Pose2D()
      if self.id is None:
        self.id = std_msgs.msg.Int16()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.position.x, _x.position.y, _x.position.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status.data = str[start:end]
      _x = self
      start = end
      end += 26
      (_x.object_state_dt.x, _x.object_state_dt.y, _x.object_state_dt.theta, _x.id.data,) = _get_struct_3dh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_3dh = None
def _get_struct_3dh():
    global _struct_3dh
    if _struct_3dh is None:
        _struct_3dh = struct.Struct("<3dh")
    return _struct_3dh
